/**
 * Who the approval request is actually addressed to.
 *
 * Deliberately code and not part of the compiled pricing book. The book is
 * compiled from the pricing sources, and the Acquirer Guidance email names roles
 * — "Regional Leader", "CRO" — not mailboxes. Mapping a role to a person is an
 * org fact that changes when someone moves job, so it lives here where it can be
 * edited without recompiling a rate card. `data/pricing-book.json` is gitignored
 * and regenerated by `npm run book:compile`; anything put there would be lost.
 *
 * Routing, in the order it is applied:
 *
 *   1. Gold track  -> Paul Goodwin. Gold is routed through him whatever the band.
 *   2. Managed by Strategic Pricing -> the Strategic Pricing mailbox. Above 25%
 *      discount the rep stops owning the email; SP manages it to the CRO/CEO.
 *   3. Otherwise    -> the named owner of the most senior role in the chain.
 *
 * Roles with no named owner yet fall through to Strategic Pricing rather than
 * producing an empty To: field. Add them below as they are confirmed.
 */

import type { ApprovalOutcome } from './types.ts';
import { sortApprovers } from './engine/approvals.ts';

export interface Approver {
  /** Used to greet the recipient by name in the draft. */
  firstName: string;
  name: string;
  email: string;
  /** Shown to the rep so they can see why this person is the recipient. */
  role: string;
}

/** The Strategic Pricing team mailbox. Also the fallback for unnamed roles. */
export const STRATEGIC_PRICING: Approver = {
  // Greeted as a team, because "Hey Strategic Pricing," reads like a mistake.
  firstName: 'Strategic Pricing team',
  name: 'Strategic Pricing Team',
  email: 'strategic.pricing@checkout.com',
  role: 'Strategic Pricing',
};

/** Gold deals — and anything over $1bn — route through here. */
export const GOLD_OWNER: Approver = {
  firstName: 'Paul',
  name: 'Paul Goodwin',
  email: 'paul.goodwin@checkout.com',
  role: 'Gold deal owner',
};

/**
 * Named owners by role. Keyed on the role strings the approval matrix emits, so a
 * new band in the book that names a role listed here is addressed automatically.
 */
export const ROLE_OWNERS: Record<string, Approver> = {
  'Regional Leader': {
    firstName: 'Ashley',
    name: 'Ashley Paulus',
    email: 'ashley.paulus@checkout.com',
    role: 'Regional Leader',
  },
  'Strategic Pricing': STRATEGIC_PRICING,
};

export interface Recipient extends Approver {
  /** One line the rep can read to understand the routing. */
  why: string;
}

/**
 * Resolves the single recipient for the approval email.
 *
 * One recipient, not a chain: the ladders put two or three names on a deal, but
 * somebody has to receive the mail and drive it. That is the most senior named
 * owner, or the team that manages the escalation on the rep's behalf.
 */
export function resolveRecipient(approval: ApprovalOutcome): Recipient | null {
  if (!approval.required) return null;

  const chain = sortApprovers(approval.approvers).map((a) => a.name);

  if (approval.track === 'gold') {
    return {
      ...GOLD_OWNER,
      why: `Gold deal — routed through ${GOLD_OWNER.name}${
        chain.length ? `, who takes it to ${chain.join(' and ')}` : ''
      }.`,
    };
  }

  if (approval.managedBy === 'Strategic Pricing') {
    return {
      ...STRATEGIC_PRICING,
      why: `Strategic Pricing manages this approval${chain.length ? ` to ${chain.join(' and ')}` : ''}.`,
    };
  }

  // Most senior first: a chain of Regional Leader + CRO is the CRO's to answer.
  for (const role of [...chain].reverse()) {
    const owner = ROLE_OWNERS[role];
    if (owner) return { ...owner, why: `${owner.name} approves as ${role}.` };
  }

  return {
    ...STRATEGIC_PRICING,
    why: `No named owner yet for ${chain.join(' or ') || 'this approval'} — routed to Strategic Pricing.`,
  };
}
